
// NPC XP 1000000-1010000 => 1005000
IF
	CheckStatLT(LastSummonerOf(Myself),1011000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1005000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1011000-1021000 => 1016000
IF
	CheckStatLT(LastSummonerOf(Myself),1022000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1016000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1022000-1032000 => 1027000
IF
	CheckStatLT(LastSummonerOf(Myself),1033000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1027000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1033000-1043000 => 1038000
IF
	CheckStatLT(LastSummonerOf(Myself),1044000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1038000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1044000-1054000 => 1049000
IF
	CheckStatLT(LastSummonerOf(Myself),1055000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1049000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1055000-1066000 => 1060000
IF
	CheckStatLT(LastSummonerOf(Myself),1067000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1060000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1067000-1078000 => 1072000
IF
	CheckStatLT(LastSummonerOf(Myself),1079000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1072000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1079000-1090000 => 1084000
IF
	CheckStatLT(LastSummonerOf(Myself),1091000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1084000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1091000-1102000 => 1096000
IF
	CheckStatLT(LastSummonerOf(Myself),1103000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1096000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1103000-1114000 => 1109000
IF
	CheckStatLT(LastSummonerOf(Myself),1115000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1109000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1115000-1126000 => 1121000
IF
	CheckStatLT(LastSummonerOf(Myself),1127000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1121000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1127000-1138000 => 1133000
IF
	CheckStatLT(LastSummonerOf(Myself),1139000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1133000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1139000-1150000 => 1145000
IF
	CheckStatLT(LastSummonerOf(Myself),1151000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1145000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1151000-1163000 => 1157000
IF
	CheckStatLT(LastSummonerOf(Myself),1164000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1157000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1164000-1176000 => 1170000
IF
	CheckStatLT(LastSummonerOf(Myself),1177000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1170000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1177000-1189000 => 1183000
IF
	CheckStatLT(LastSummonerOf(Myself),1190000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1183000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1190000-1202000 => 1196000
IF
	CheckStatLT(LastSummonerOf(Myself),1203000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1196000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1203000-1215000 => 1209000
IF
	CheckStatLT(LastSummonerOf(Myself),1216000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1209000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1216000-1228000 => 1222000
IF
	CheckStatLT(LastSummonerOf(Myself),1229000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1222000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1229000-1241000 => 1235000
IF
	CheckStatLT(LastSummonerOf(Myself),1242000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1235000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1242000-1254000 => 1248000
IF
	CheckStatLT(LastSummonerOf(Myself),1255000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1248000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1255000-1268000 => 1261000
IF
	CheckStatLT(LastSummonerOf(Myself),1269000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1261000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1269000-1282000 => 1275000
IF
	CheckStatLT(LastSummonerOf(Myself),1283000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1275000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1283000-1296000 => 1289000
IF
	CheckStatLT(LastSummonerOf(Myself),1297000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1289000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1297000-1310000 => 1303000
IF
	CheckStatLT(LastSummonerOf(Myself),1311000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1303000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1311000-1324000 => 1318000
IF
	CheckStatLT(LastSummonerOf(Myself),1325000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1318000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1325000-1338000 => 1332000
IF
	CheckStatLT(LastSummonerOf(Myself),1339000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1332000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1339000-1352000 => 1346000
IF
	CheckStatLT(LastSummonerOf(Myself),1353000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1346000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1353000-1367000 => 1360000
IF
	CheckStatLT(LastSummonerOf(Myself),1368000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1360000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1368000-1382000 => 1375000
IF
	CheckStatLT(LastSummonerOf(Myself),1383000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1375000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1383000-1397000 => 1390000
IF
	CheckStatLT(LastSummonerOf(Myself),1398000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1390000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1398000-1412000 => 1405000
IF
	CheckStatLT(LastSummonerOf(Myself),1413000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1405000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1413000-1427000 => 1420000
IF
	CheckStatLT(LastSummonerOf(Myself),1428000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1420000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1428000-1442000 => 1435000
IF
	CheckStatLT(LastSummonerOf(Myself),1443000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1435000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1443000-1457000 => 1450000
IF
	CheckStatLT(LastSummonerOf(Myself),1458000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1450000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1458000-1473000 => 1465000
IF
	CheckStatLT(LastSummonerOf(Myself),1474000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1465000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1474000-1489000 => 1481000
IF
	CheckStatLT(LastSummonerOf(Myself),1490000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1481000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1490000-1505000 => 1497000
IF
	CheckStatLT(LastSummonerOf(Myself),1506000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1497000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1506000-1521000 => 1514000
IF
	CheckStatLT(LastSummonerOf(Myself),1522000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1514000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1522000-1537000 => 1530000
IF
	CheckStatLT(LastSummonerOf(Myself),1538000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1530000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1538000-1553000 => 1546000
IF
	CheckStatLT(LastSummonerOf(Myself),1554000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1546000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1554000-1570000 => 1562000
IF
	CheckStatLT(LastSummonerOf(Myself),1571000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1562000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1571000-1587000 => 1579000
IF
	CheckStatLT(LastSummonerOf(Myself),1588000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1579000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1588000-1604000 => 1596000
IF
	CheckStatLT(LastSummonerOf(Myself),1605000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1596000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1605000-1621000 => 1613000
IF
	CheckStatLT(LastSummonerOf(Myself),1622000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1613000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1622000-1638000 => 1630000
IF
	CheckStatLT(LastSummonerOf(Myself),1639000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1630000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1639000-1655000 => 1647000
IF
	CheckStatLT(LastSummonerOf(Myself),1656000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1647000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1656000-1673000 => 1664000
IF
	CheckStatLT(LastSummonerOf(Myself),1674000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1664000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1674000-1691000 => 1682000
IF
	CheckStatLT(LastSummonerOf(Myself),1692000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1682000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1692000-1709000 => 1700000
IF
	CheckStatLT(LastSummonerOf(Myself),1710000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1700000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1710000-1727000 => 1719000
IF
	CheckStatLT(LastSummonerOf(Myself),1728000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1719000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1728000-1745000 => 1737000
IF
	CheckStatLT(LastSummonerOf(Myself),1746000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1737000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1746000-1763000 => 1755000
IF
	CheckStatLT(LastSummonerOf(Myself),1764000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1755000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1764000-1782000 => 1773000
IF
	CheckStatLT(LastSummonerOf(Myself),1783000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1773000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1783000-1801000 => 1792000
IF
	CheckStatLT(LastSummonerOf(Myself),1802000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1792000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1802000-1820000 => 1811000
IF
	CheckStatLT(LastSummonerOf(Myself),1821000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1811000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1821000-1839000 => 1830000
IF
	CheckStatLT(LastSummonerOf(Myself),1840000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1830000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1840000-1858000 => 1849000
IF
	CheckStatLT(LastSummonerOf(Myself),1859000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1849000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1859000-1878000 => 1868000
IF
	CheckStatLT(LastSummonerOf(Myself),1879000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1868000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1879000-1898000 => 1888000
IF
	CheckStatLT(LastSummonerOf(Myself),1899000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1888000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1899000-1918000 => 1908000
IF
	CheckStatLT(LastSummonerOf(Myself),1919000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1908000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1919000-1938000 => 1929000
IF
	CheckStatLT(LastSummonerOf(Myself),1939000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1929000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1939000-1958000 => 1949000
IF
	CheckStatLT(LastSummonerOf(Myself),1959000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1949000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1959000-1979000 => 1969000
IF
	CheckStatLT(LastSummonerOf(Myself),1980000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1969000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1980000-2000000 => 1990000
IF
	CheckStatLT(LastSummonerOf(Myself),2001000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1990000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2001000-2021000 => 2011000
IF
	CheckStatLT(LastSummonerOf(Myself),2022000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2011000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2022000-2042000 => 2032000
IF
	CheckStatLT(LastSummonerOf(Myself),2043000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2032000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2043000-2063000 => 2053000
IF
	CheckStatLT(LastSummonerOf(Myself),2064000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2053000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2064000-2085000 => 2074000
IF
	CheckStatLT(LastSummonerOf(Myself),2086000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2074000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2086000-2107000 => 2096000
IF
	CheckStatLT(LastSummonerOf(Myself),2108000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2096000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2108000-2129000 => 2119000
IF
	CheckStatLT(LastSummonerOf(Myself),2130000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2119000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2130000-2151000 => 2141000
IF
	CheckStatLT(LastSummonerOf(Myself),2152000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2141000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2152000-2174000 => 2163000
IF
	CheckStatLT(LastSummonerOf(Myself),2175000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2163000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2175000-2197000 => 2186000
IF
	CheckStatLT(LastSummonerOf(Myself),2198000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2186000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2198000-2220000 => 2209000
IF
	CheckStatLT(LastSummonerOf(Myself),2221000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2209000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2221000-2243000 => 2232000
IF
	CheckStatLT(LastSummonerOf(Myself),2244000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2232000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2244000-2266000 => 2255000
IF
	CheckStatLT(LastSummonerOf(Myself),2267000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2255000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2267000-2290000 => 2278000
IF
	CheckStatLT(LastSummonerOf(Myself),2291000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2278000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2291000-2314000 => 2302000
IF
	CheckStatLT(LastSummonerOf(Myself),2315000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2302000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2315000-2338000 => 2327000
IF
	CheckStatLT(LastSummonerOf(Myself),2339000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2327000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2339000-2362000 => 2351000
IF
	CheckStatLT(LastSummonerOf(Myself),2363000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2351000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2363000-2387000 => 2375000
IF
	CheckStatLT(LastSummonerOf(Myself),2388000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2375000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2388000-2412000 => 2400000
IF
	CheckStatLT(LastSummonerOf(Myself),2413000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2400000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2413000-2437000 => 2425000
IF
	CheckStatLT(LastSummonerOf(Myself),2438000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2425000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2438000-2462000 => 2450000
IF
	CheckStatLT(LastSummonerOf(Myself),2463000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2450000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2463000-2488000 => 2475000
IF
	CheckStatLT(LastSummonerOf(Myself),2489000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2475000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2489000-2514000 => 2501000
IF
	CheckStatLT(LastSummonerOf(Myself),2515000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2501000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2515000-2540000 => 2528000
IF
	CheckStatLT(LastSummonerOf(Myself),2541000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2528000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2541000-2566000 => 2554000
IF
	CheckStatLT(LastSummonerOf(Myself),2567000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2554000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2567000-2593000 => 2580000
IF
	CheckStatLT(LastSummonerOf(Myself),2594000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2580000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2594000-2620000 => 2607000
IF
	CheckStatLT(LastSummonerOf(Myself),2621000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2607000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2621000-2647000 => 2634000
IF
	CheckStatLT(LastSummonerOf(Myself),2648000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2634000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2648000-2674000 => 2661000
IF
	CheckStatLT(LastSummonerOf(Myself),2675000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2661000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2675000-2702000 => 2688000
IF
	CheckStatLT(LastSummonerOf(Myself),2703000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2688000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2703000-2730000 => 2717000
IF
	CheckStatLT(LastSummonerOf(Myself),2731000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2717000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2731000-2758000 => 2745000
IF
	CheckStatLT(LastSummonerOf(Myself),2759000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2745000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2759000-2787000 => 2773000
IF
	CheckStatLT(LastSummonerOf(Myself),2788000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2773000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2788000-2816000 => 2802000
IF
	CheckStatLT(LastSummonerOf(Myself),2817000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2802000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2817000-2845000 => 2831000
IF
	CheckStatLT(LastSummonerOf(Myself),2846000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2831000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2846000-2874000 => 2860000
IF
	CheckStatLT(LastSummonerOf(Myself),2875000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2860000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2875000-2904000 => 2889000
IF
	CheckStatLT(LastSummonerOf(Myself),2905000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2889000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2905000-2934000 => 2920000
IF
	CheckStatLT(LastSummonerOf(Myself),2935000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2920000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2935000-2964000 => 2950000
IF
	CheckStatLT(LastSummonerOf(Myself),2965000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2950000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2965000-2995000 => 2980000
IF
	CheckStatLT(LastSummonerOf(Myself),2996000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2980000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2996000-3026000 => 3011000
IF
	CheckStatLT(LastSummonerOf(Myself),3027000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3011000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3027000-3057000 => 3042000
IF
	CheckStatLT(LastSummonerOf(Myself),3058000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3042000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3058000-3089000 => 3073000
IF
	CheckStatLT(LastSummonerOf(Myself),3090000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3073000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3090000-3121000 => 3105000
IF
	CheckStatLT(LastSummonerOf(Myself),3122000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3105000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3122000-3153000 => 3138000
IF
	CheckStatLT(LastSummonerOf(Myself),3154000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3138000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3154000-3186000 => 3170000
IF
	CheckStatLT(LastSummonerOf(Myself),3187000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3170000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3187000-3219000 => 3203000
IF
	CheckStatLT(LastSummonerOf(Myself),3220000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3203000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3220000-3252000 => 3236000
IF
	CheckStatLT(LastSummonerOf(Myself),3253000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3236000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3253000-3286000 => 3269000
IF
	CheckStatLT(LastSummonerOf(Myself),3287000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3269000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3287000-3320000 => 3303000
IF
	CheckStatLT(LastSummonerOf(Myself),3321000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3303000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3321000-3354000 => 3338000
IF
	CheckStatLT(LastSummonerOf(Myself),3355000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3338000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3355000-3389000 => 3372000
IF
	CheckStatLT(LastSummonerOf(Myself),3390000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3372000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3390000-3424000 => 3407000
IF
	CheckStatLT(LastSummonerOf(Myself),3425000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3407000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3425000-3459000 => 3442000
IF
	CheckStatLT(LastSummonerOf(Myself),3460000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3442000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3460000-3495000 => 3477000
IF
	CheckStatLT(LastSummonerOf(Myself),3496000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3477000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3496000-3531000 => 3513000
IF
	CheckStatLT(LastSummonerOf(Myself),3532000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3513000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3532000-3567000 => 3550000
IF
	CheckStatLT(LastSummonerOf(Myself),3568000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3550000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3568000-3604000 => 3586000
IF
	CheckStatLT(LastSummonerOf(Myself),3605000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3586000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3605000-3641000 => 3623000
IF
	CheckStatLT(LastSummonerOf(Myself),3642000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3623000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3642000-3678000 => 3660000
IF
	CheckStatLT(LastSummonerOf(Myself),3679000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3660000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3679000-3716000 => 3697000
IF
	CheckStatLT(LastSummonerOf(Myself),3717000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3697000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3717000-3754000 => 3736000
IF
	CheckStatLT(LastSummonerOf(Myself),3755000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3736000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3755000-3793000 => 3774000
IF
	CheckStatLT(LastSummonerOf(Myself),3794000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3774000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3794000-3832000 => 3813000
IF
	CheckStatLT(LastSummonerOf(Myself),3833000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3813000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3833000-3871000 => 3852000
IF
	CheckStatLT(LastSummonerOf(Myself),3872000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3852000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3872000-3911000 => 3891000
IF
	CheckStatLT(LastSummonerOf(Myself),3912000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3891000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3912000-3951000 => 3932000
IF
	CheckStatLT(LastSummonerOf(Myself),3952000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3932000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3952000-3992000 => 3972000
IF
	CheckStatLT(LastSummonerOf(Myself),3993000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3972000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3993000-4033000 => 4013000
IF
	CheckStatLT(LastSummonerOf(Myself),4034000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4013000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4034000-4074000 => 4054000
IF
	CheckStatLT(LastSummonerOf(Myself),4075000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4054000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4075000-4116000 => 4095000
IF
	CheckStatLT(LastSummonerOf(Myself),4117000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4095000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4117000-4158000 => 4138000
IF
	CheckStatLT(LastSummonerOf(Myself),4159000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4138000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4159000-4201000 => 4180000
IF
	CheckStatLT(LastSummonerOf(Myself),4202000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4180000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4202000-4244000 => 4223000
IF
	CheckStatLT(LastSummonerOf(Myself),4245000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4223000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4245000-4287000 => 4266000
IF
	CheckStatLT(LastSummonerOf(Myself),4288000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4266000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4288000-4331000 => 4309000
IF
	CheckStatLT(LastSummonerOf(Myself),4332000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4309000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4332000-4375000 => 4354000
IF
	CheckStatLT(LastSummonerOf(Myself),4376000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4354000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4376000-4420000 => 4398000
IF
	CheckStatLT(LastSummonerOf(Myself),4421000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4398000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4421000-4465000 => 4443000
IF
	CheckStatLT(LastSummonerOf(Myself),4466000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4443000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4466000-4511000 => 4488000
IF
	CheckStatLT(LastSummonerOf(Myself),4512000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4488000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4512000-4557000 => 4535000
IF
	CheckStatLT(LastSummonerOf(Myself),4558000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4535000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4558000-4604000 => 4581000
IF
	CheckStatLT(LastSummonerOf(Myself),4605000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4581000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4605000-4651000 => 4628000
IF
	CheckStatLT(LastSummonerOf(Myself),4652000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4628000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4652000-4699000 => 4675000
IF
	CheckStatLT(LastSummonerOf(Myself),4700000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4675000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4700000-4747000 => 4723000
IF
	CheckStatLT(LastSummonerOf(Myself),4748000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4723000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4748000-4795000 => 4772000
IF
	CheckStatLT(LastSummonerOf(Myself),4796000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4772000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4796000-4844000 => 4820000
IF
	CheckStatLT(LastSummonerOf(Myself),4845000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4820000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4845000-4893000 => 4869000
IF
	CheckStatLT(LastSummonerOf(Myself),4894000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4869000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4894000-4943000 => 4918000
IF
	CheckStatLT(LastSummonerOf(Myself),4944000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4918000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4944000-4993000 => 4969000
IF
	CheckStatLT(LastSummonerOf(Myself),4994000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4969000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4994000-5044000 => 5019000
IF
	CheckStatLT(LastSummonerOf(Myself),5045000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5019000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5045000-5095000 => 5070000
IF
	CheckStatLT(LastSummonerOf(Myself),5096000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5070000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5096000-5147000 => 5121000
IF
	CheckStatLT(LastSummonerOf(Myself),5148000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5121000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5148000-5199000 => 5174000
IF
	CheckStatLT(LastSummonerOf(Myself),5200000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5174000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5200000-5252000 => 5226000
IF
	CheckStatLT(LastSummonerOf(Myself),5253000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5226000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5253000-5306000 => 5279000
IF
	CheckStatLT(LastSummonerOf(Myself),5307000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5279000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5307000-5360000 => 5334000
IF
	CheckStatLT(LastSummonerOf(Myself),5361000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5334000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5361000-5415000 => 5388000
IF
	CheckStatLT(LastSummonerOf(Myself),5416000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5388000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5416000-5470000 => 5443000
IF
	CheckStatLT(LastSummonerOf(Myself),5471000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5443000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5471000-5526000 => 5498000
IF
	CheckStatLT(LastSummonerOf(Myself),5527000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5498000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5527000-5582000 => 5555000
IF
	CheckStatLT(LastSummonerOf(Myself),5583000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5555000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5583000-5639000 => 5611000
IF
	CheckStatLT(LastSummonerOf(Myself),5640000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5611000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5640000-5696000 => 5668000
IF
	CheckStatLT(LastSummonerOf(Myself),5697000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5668000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5697000-5754000 => 5725000
IF
	CheckStatLT(LastSummonerOf(Myself),5755000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5725000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5755000-5813000 => 5784000
IF
	CheckStatLT(LastSummonerOf(Myself),5814000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5784000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5814000-5872000 => 5843000
IF
	CheckStatLT(LastSummonerOf(Myself),5873000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5843000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5873000-5932000 => 5902000
IF
	CheckStatLT(LastSummonerOf(Myself),5933000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5902000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5933000-5992000 => 5963000
IF
	CheckStatLT(LastSummonerOf(Myself),5993000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5963000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5993000-6053000 => 6023000
IF
	CheckStatLT(LastSummonerOf(Myself),6054000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6023000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6054000-6115000 => 6084000
IF
	CheckStatLT(LastSummonerOf(Myself),6116000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6084000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6116000-6177000 => 6147000
IF
	CheckStatLT(LastSummonerOf(Myself),6178000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6147000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6178000-6240000 => 6209000
IF
	CheckStatLT(LastSummonerOf(Myself),6241000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6209000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6241000-6303000 => 6272000
IF
	CheckStatLT(LastSummonerOf(Myself),6304000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6272000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6304000-6367000 => 6336000
IF
	CheckStatLT(LastSummonerOf(Myself),6368000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6336000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6368000-6432000 => 6400000
IF
	CheckStatLT(LastSummonerOf(Myself),6433000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6400000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6433000-6497000 => 6465000
IF
	CheckStatLT(LastSummonerOf(Myself),6498000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6465000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6498000-6563000 => 6530000
IF
	CheckStatLT(LastSummonerOf(Myself),6564000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6530000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6564000-6630000 => 6597000
IF
	CheckStatLT(LastSummonerOf(Myself),6631000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6597000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6631000-6697000 => 6664000
IF
	CheckStatLT(LastSummonerOf(Myself),6698000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6664000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6698000-6765000 => 6731000
IF
	CheckStatLT(LastSummonerOf(Myself),6766000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6731000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6766000-6834000 => 6800000
IF
	CheckStatLT(LastSummonerOf(Myself),6835000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6800000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6835000-6903000 => 6869000
IF
	CheckStatLT(LastSummonerOf(Myself),6904000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6869000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6904000-6973000 => 6939000
IF
	CheckStatLT(LastSummonerOf(Myself),6974000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6939000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6974000-7044000 => 7009000
IF
	CheckStatLT(LastSummonerOf(Myself),7045000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7009000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7045000-7115000 => 7080000
IF
	CheckStatLT(LastSummonerOf(Myself),7116000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7080000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7116000-7187000 => 7152000
IF
	CheckStatLT(LastSummonerOf(Myself),7188000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7152000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7188000-7260000 => 7224000
IF
	CheckStatLT(LastSummonerOf(Myself),7261000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7224000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7261000-7334000 => 7297000
IF
	CheckStatLT(LastSummonerOf(Myself),7335000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7297000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7335000-7408000 => 7372000
IF
	CheckStatLT(LastSummonerOf(Myself),7409000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7372000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7409000-7483000 => 7446000
IF
	CheckStatLT(LastSummonerOf(Myself),7484000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7446000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7484000-7559000 => 7521000
IF
	CheckStatLT(LastSummonerOf(Myself),7560000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7521000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7560000-7636000 => 7598000
IF
	CheckStatLT(LastSummonerOf(Myself),7637000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7598000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7637000-7713000 => 7675000
IF
	CheckStatLT(LastSummonerOf(Myself),7714000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7675000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7714000-7791000 => 7753000
IF
	CheckStatLT(LastSummonerOf(Myself),7792000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7753000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7792000-7870000 => 7831000
IF
	CheckStatLT(LastSummonerOf(Myself),7871000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7831000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7871000-7950000 => 7910000
IF
	CheckStatLT(LastSummonerOf(Myself),7951000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7910000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7951000-8031000 => 7991000
IF
	CheckStatLT(LastSummonerOf(Myself),8032000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7991000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8032000-8112000 => 8072000
IF
	CheckStatLT(LastSummonerOf(Myself),8113000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8072000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8113000-8194000 => 8154000
IF
	CheckStatLT(LastSummonerOf(Myself),8195000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8154000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8195000-8277000 => 8236000
IF
	CheckStatLT(LastSummonerOf(Myself),8278000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8236000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8278000-8361000 => 8319000
IF
	CheckStatLT(LastSummonerOf(Myself),8362000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8319000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8362000-8446000 => 8404000
IF
	CheckStatLT(LastSummonerOf(Myself),8447000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8404000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8447000-8531000 => 8489000
IF
	CheckStatLT(LastSummonerOf(Myself),8532000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8489000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8532000-8617000 => 8575000
IF
	CheckStatLT(LastSummonerOf(Myself),8618000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8575000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8618000-8704000 => 8661000
IF
	CheckStatLT(LastSummonerOf(Myself),8705000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8661000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8705000-8792000 => 8749000
IF
	CheckStatLT(LastSummonerOf(Myself),8793000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8749000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8793000-8881000 => 8837000
IF
	CheckStatLT(LastSummonerOf(Myself),8882000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8837000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8882000-8971000 => 8926000
IF
	CheckStatLT(LastSummonerOf(Myself),8972000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8926000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8972000-9062000 => 9017000
IF
	CheckStatLT(LastSummonerOf(Myself),9063000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9017000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9063000-9154000 => 9108000
IF
	CheckStatLT(LastSummonerOf(Myself),9155000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9108000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9155000-9247000 => 9201000
IF
	CheckStatLT(LastSummonerOf(Myself),9248000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9201000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9248000-9340000 => 9294000
IF
	CheckStatLT(LastSummonerOf(Myself),9341000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9294000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9341000-9434000 => 9388000
IF
	CheckStatLT(LastSummonerOf(Myself),9435000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9388000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9435000-9529000 => 9482000
IF
	CheckStatLT(LastSummonerOf(Myself),9530000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9482000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9530000-9625000 => 9578000
IF
	CheckStatLT(LastSummonerOf(Myself),9626000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9578000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9626000-9722000 => 9674000
IF
	CheckStatLT(LastSummonerOf(Myself),9723000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9674000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9723000-9820000 => 9772000
IF
	CheckStatLT(LastSummonerOf(Myself),9821000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9772000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9821000-9919000 => 9870000
IF
	CheckStatLT(LastSummonerOf(Myself),9920000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9870000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9920000-10019000 => 9970000
IF
	CheckStatLT(LastSummonerOf(Myself),10020000,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9970000)
		ChangeAIScript("xpsgrant",OVERRIDE)
END
