// LastSummonerOf(Myself) is a dual class, with original class PALADIN
// Go through levels and adjust XP
IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,2)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_2_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,3)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_3_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,4)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_4_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,5)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_5_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,6)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_6_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,7)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_7_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,8)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_8_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,9)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_9_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,10)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_10_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,11)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_11_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,12)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_12_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,13)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_13_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,14)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_14_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,15)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_15_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,16)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_16_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,17)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_17_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,18)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_18_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,19)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_19_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,20)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_20_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,21)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_21_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,22)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_22_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,23)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_23_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,24)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_24_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,25)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_25_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,26)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_26_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,27)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_27_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,28)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_28_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,29)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_29_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,30)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_30_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,31)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_31_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,32)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_32_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,33)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_33_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,34)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_34_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,35)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_35_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,36)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_36_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,37)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_37_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,38)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_38_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,39)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_39_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,40)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%PALADIN_40_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

 // No matches so weirdness or have a dual class greater than our range
IF
	True()
THEN
	RESPONSE #100
		ChangeAIScript("xps_wipe",OVERRIDE)
END

