// LastSummonerOf(Myself) is a dual class, with original class SORCERER
// Go through levels and adjust XP
IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,2)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_2_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,3)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_3_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,4)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_4_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,5)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_5_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,6)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_6_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,7)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_7_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,8)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_8_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,9)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_9_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,10)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_10_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,11)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_11_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,12)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_12_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,13)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_13_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,14)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_14_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,15)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_15_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,16)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_16_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,17)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_17_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,18)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_18_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,19)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_19_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,20)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_20_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,21)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_21_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,22)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_22_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,23)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_23_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,24)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_24_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,25)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_25_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,26)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_26_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,27)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_27_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,28)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_28_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,29)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_29_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,30)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_30_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,31)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_31_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,32)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_32_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,33)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_33_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,34)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_34_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,35)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_35_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,36)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_36_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,37)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_37_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,38)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_38_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,39)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_39_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WIZARD,40)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%SORCERER_40_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

 // No matches so weirdness or have a dual class greater than our range
IF
	True()
THEN
	RESPONSE #100
		ChangeAIScript("xps_wipe",OVERRIDE)
END

