// Player1 is a dual class, with original class RANGER
// Go through levels and adjust XP
IF
	ClassLevel(Player1,WARRIOR,2)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_2_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,3)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_3_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,4)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_4_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,5)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_5_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,6)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_6_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,7)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_7_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,8)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_8_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,9)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_9_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,10)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_10_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,11)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_11_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,12)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_12_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,13)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_13_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,14)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_14_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,15)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_15_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,16)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_16_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,17)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_17_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,18)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_18_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,19)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_19_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,20)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_20_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,21)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_21_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,22)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_22_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,23)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_23_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,24)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_24_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,25)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_25_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,26)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_26_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,27)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_27_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,28)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_28_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,29)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_29_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,30)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_30_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,31)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_31_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,32)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_32_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,33)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_33_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,34)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_34_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,35)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_35_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,36)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_36_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,37)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_37_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,38)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_38_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,39)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_39_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,WARRIOR,40)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%RANGER_40_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

 // No matches so weirdness or have a dual class greater than our range
IF
	True()
THEN
	RESPONSE #100
		ChangeAIScript("xps_nd",OVERRIDE)
END

