// LastSummonerOf(Myself) is a dual class, with original class FIGHTER
// Go through levels and adjust XP
IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,2)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_2_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,3)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_3_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,4)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_4_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,5)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_5_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,6)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_6_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,7)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_7_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,8)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_8_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,9)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_9_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,10)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_10_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,11)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_11_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,12)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_12_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,13)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_13_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,14)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_14_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,15)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_15_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,16)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_16_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,17)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_17_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,18)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_18_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,19)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_19_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,20)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_20_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,21)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_21_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,22)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_22_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,23)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_23_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,24)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_24_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,25)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_25_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,26)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_26_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,27)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_27_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,28)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_28_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,29)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_29_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,30)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_30_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,31)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_31_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,32)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_32_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,33)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_33_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,34)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_34_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,35)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_35_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,36)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_36_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,37)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_37_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,38)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_38_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,39)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_39_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

IF
	ClassLevel(LastSummonerOf(Myself),WARRIOR,40)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-%FIGHTER_40_XP%)
		ChangeAIScript("xps_wipe",OVERRIDE)
END

 // No matches so weirdness or have a dual class greater than our range
IF
	True()
THEN
	RESPONSE #100
		ChangeAIScript("xps_wipe",OVERRIDE)
END

