// Player1 is a dual class, with original class CLASSNAME
// Go through levels and adjust XP
IF
	ClassLevel(Player1,CLSCAT,2)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_2_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,3)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_3_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,4)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_4_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,5)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_5_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,6)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_6_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,7)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_7_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,8)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_8_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,9)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_9_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,10)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_10_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,11)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_11_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,12)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_12_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,13)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_13_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,14)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_14_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,15)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_15_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,16)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_16_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,17)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_17_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,18)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_18_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,19)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_19_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,20)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_20_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,21)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_21_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,22)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_22_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,23)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_23_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,24)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_24_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,25)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_25_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,26)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_26_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,27)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_27_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,28)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_28_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,29)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_29_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,30)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_30_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,31)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_31_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,32)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_32_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,33)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_33_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,34)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_34_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,35)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_35_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,36)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_36_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,37)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_37_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,38)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_38_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,39)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_39_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

IF
	ClassLevel(Player1,CLSCAT,40)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",%CLASSNAME_40_XP%)
		ChangeAIScript("xps_nd",OVERRIDE)
END

 // No matches so weirdness or have a dual class greater than our range
IF
	True()
THEN
	RESPONSE #100
		ChangeAIScript("xps_nd",OVERRIDE)
END

