
// NPC XP 1000POW-1010POW => 1005POW
IF
	CheckStatLT(LastSummonerOf(Myself),1011POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1005POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1011POW-1021POW => 1016POW
IF
	CheckStatLT(LastSummonerOf(Myself),1022POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1016POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1022POW-1032POW => 1027POW
IF
	CheckStatLT(LastSummonerOf(Myself),1033POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1027POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1033POW-1043POW => 1038POW
IF
	CheckStatLT(LastSummonerOf(Myself),1044POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1038POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1044POW-1054POW => 1049POW
IF
	CheckStatLT(LastSummonerOf(Myself),1055POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1049POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1055POW-1066POW => 1060POW
IF
	CheckStatLT(LastSummonerOf(Myself),1067POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1060POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1067POW-1078POW => 1072POW
IF
	CheckStatLT(LastSummonerOf(Myself),1079POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1072POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1079POW-1090POW => 1084POW
IF
	CheckStatLT(LastSummonerOf(Myself),1091POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1084POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1091POW-1102POW => 1096POW
IF
	CheckStatLT(LastSummonerOf(Myself),1103POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1096POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1103POW-1114POW => 1109POW
IF
	CheckStatLT(LastSummonerOf(Myself),1115POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1109POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1115POW-1126POW => 1121POW
IF
	CheckStatLT(LastSummonerOf(Myself),1127POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1121POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1127POW-1138POW => 1133POW
IF
	CheckStatLT(LastSummonerOf(Myself),1139POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1133POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1139POW-1150POW => 1145POW
IF
	CheckStatLT(LastSummonerOf(Myself),1151POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1145POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1151POW-1163POW => 1157POW
IF
	CheckStatLT(LastSummonerOf(Myself),1164POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1157POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1164POW-1176POW => 1170POW
IF
	CheckStatLT(LastSummonerOf(Myself),1177POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1170POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1177POW-1189POW => 1183POW
IF
	CheckStatLT(LastSummonerOf(Myself),1190POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1183POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1190POW-1202POW => 1196POW
IF
	CheckStatLT(LastSummonerOf(Myself),1203POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1196POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1203POW-1215POW => 1209POW
IF
	CheckStatLT(LastSummonerOf(Myself),1216POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1209POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1216POW-1228POW => 1222POW
IF
	CheckStatLT(LastSummonerOf(Myself),1229POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1222POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1229POW-1241POW => 1235POW
IF
	CheckStatLT(LastSummonerOf(Myself),1242POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1235POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1242POW-1254POW => 1248POW
IF
	CheckStatLT(LastSummonerOf(Myself),1255POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1248POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1255POW-1268POW => 1261POW
IF
	CheckStatLT(LastSummonerOf(Myself),1269POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1261POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1269POW-1282POW => 1275POW
IF
	CheckStatLT(LastSummonerOf(Myself),1283POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1275POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1283POW-1296POW => 1289POW
IF
	CheckStatLT(LastSummonerOf(Myself),1297POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1289POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1297POW-1310POW => 1303POW
IF
	CheckStatLT(LastSummonerOf(Myself),1311POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1303POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1311POW-1324POW => 1318POW
IF
	CheckStatLT(LastSummonerOf(Myself),1325POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1318POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1325POW-1338POW => 1332POW
IF
	CheckStatLT(LastSummonerOf(Myself),1339POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1332POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1339POW-1352POW => 1346POW
IF
	CheckStatLT(LastSummonerOf(Myself),1353POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1346POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1353POW-1367POW => 1360POW
IF
	CheckStatLT(LastSummonerOf(Myself),1368POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1360POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1368POW-1382POW => 1375POW
IF
	CheckStatLT(LastSummonerOf(Myself),1383POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1375POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1383POW-1397POW => 1390POW
IF
	CheckStatLT(LastSummonerOf(Myself),1398POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1390POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1398POW-1412POW => 1405POW
IF
	CheckStatLT(LastSummonerOf(Myself),1413POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1405POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1413POW-1427POW => 1420POW
IF
	CheckStatLT(LastSummonerOf(Myself),1428POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1420POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1428POW-1442POW => 1435POW
IF
	CheckStatLT(LastSummonerOf(Myself),1443POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1435POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1443POW-1457POW => 1450POW
IF
	CheckStatLT(LastSummonerOf(Myself),1458POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1450POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1458POW-1473POW => 1465POW
IF
	CheckStatLT(LastSummonerOf(Myself),1474POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1465POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1474POW-1489POW => 1481POW
IF
	CheckStatLT(LastSummonerOf(Myself),1490POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1481POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1490POW-1505POW => 1497POW
IF
	CheckStatLT(LastSummonerOf(Myself),1506POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1497POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1506POW-1521POW => 1514POW
IF
	CheckStatLT(LastSummonerOf(Myself),1522POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1514POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1522POW-1537POW => 1530POW
IF
	CheckStatLT(LastSummonerOf(Myself),1538POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1530POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1538POW-1553POW => 1546POW
IF
	CheckStatLT(LastSummonerOf(Myself),1554POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1546POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1554POW-1570POW => 1562POW
IF
	CheckStatLT(LastSummonerOf(Myself),1571POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1562POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1571POW-1587POW => 1579POW
IF
	CheckStatLT(LastSummonerOf(Myself),1588POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1579POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1588POW-1604POW => 1596POW
IF
	CheckStatLT(LastSummonerOf(Myself),1605POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1596POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1605POW-1621POW => 1613POW
IF
	CheckStatLT(LastSummonerOf(Myself),1622POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1613POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1622POW-1638POW => 1630POW
IF
	CheckStatLT(LastSummonerOf(Myself),1639POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1630POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1639POW-1655POW => 1647POW
IF
	CheckStatLT(LastSummonerOf(Myself),1656POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1647POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1656POW-1673POW => 1664POW
IF
	CheckStatLT(LastSummonerOf(Myself),1674POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1664POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1674POW-1691POW => 1682POW
IF
	CheckStatLT(LastSummonerOf(Myself),1692POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1682POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1692POW-1709POW => 1700POW
IF
	CheckStatLT(LastSummonerOf(Myself),1710POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1700POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1710POW-1727POW => 1719POW
IF
	CheckStatLT(LastSummonerOf(Myself),1728POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1719POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1728POW-1745POW => 1737POW
IF
	CheckStatLT(LastSummonerOf(Myself),1746POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1737POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1746POW-1763POW => 1755POW
IF
	CheckStatLT(LastSummonerOf(Myself),1764POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1755POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1764POW-1782POW => 1773POW
IF
	CheckStatLT(LastSummonerOf(Myself),1783POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1773POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1783POW-1801POW => 1792POW
IF
	CheckStatLT(LastSummonerOf(Myself),1802POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1792POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1802POW-1820POW => 1811POW
IF
	CheckStatLT(LastSummonerOf(Myself),1821POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1811POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1821POW-1839POW => 1830POW
IF
	CheckStatLT(LastSummonerOf(Myself),1840POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1830POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1840POW-1858POW => 1849POW
IF
	CheckStatLT(LastSummonerOf(Myself),1859POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1849POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1859POW-1878POW => 1868POW
IF
	CheckStatLT(LastSummonerOf(Myself),1879POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1868POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1879POW-1898POW => 1888POW
IF
	CheckStatLT(LastSummonerOf(Myself),1899POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1888POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1899POW-1918POW => 1908POW
IF
	CheckStatLT(LastSummonerOf(Myself),1919POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1908POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1919POW-1938POW => 1929POW
IF
	CheckStatLT(LastSummonerOf(Myself),1939POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1929POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1939POW-1958POW => 1949POW
IF
	CheckStatLT(LastSummonerOf(Myself),1959POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1949POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1959POW-1979POW => 1969POW
IF
	CheckStatLT(LastSummonerOf(Myself),1980POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1969POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 1980POW-2000POW => 1990POW
IF
	CheckStatLT(LastSummonerOf(Myself),2001POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-1990POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2001POW-2021POW => 2011POW
IF
	CheckStatLT(LastSummonerOf(Myself),2022POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2011POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2022POW-2042POW => 2032POW
IF
	CheckStatLT(LastSummonerOf(Myself),2043POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2032POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2043POW-2063POW => 2053POW
IF
	CheckStatLT(LastSummonerOf(Myself),2064POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2053POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2064POW-2085POW => 2074POW
IF
	CheckStatLT(LastSummonerOf(Myself),2086POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2074POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2086POW-2107POW => 2096POW
IF
	CheckStatLT(LastSummonerOf(Myself),2108POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2096POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2108POW-2129POW => 2119POW
IF
	CheckStatLT(LastSummonerOf(Myself),2130POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2119POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2130POW-2151POW => 2141POW
IF
	CheckStatLT(LastSummonerOf(Myself),2152POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2141POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2152POW-2174POW => 2163POW
IF
	CheckStatLT(LastSummonerOf(Myself),2175POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2163POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2175POW-2197POW => 2186POW
IF
	CheckStatLT(LastSummonerOf(Myself),2198POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2186POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2198POW-2220POW => 2209POW
IF
	CheckStatLT(LastSummonerOf(Myself),2221POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2209POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2221POW-2243POW => 2232POW
IF
	CheckStatLT(LastSummonerOf(Myself),2244POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2232POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2244POW-2266POW => 2255POW
IF
	CheckStatLT(LastSummonerOf(Myself),2267POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2255POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2267POW-2290POW => 2278POW
IF
	CheckStatLT(LastSummonerOf(Myself),2291POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2278POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2291POW-2314POW => 2302POW
IF
	CheckStatLT(LastSummonerOf(Myself),2315POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2302POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2315POW-2338POW => 2327POW
IF
	CheckStatLT(LastSummonerOf(Myself),2339POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2327POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2339POW-2362POW => 2351POW
IF
	CheckStatLT(LastSummonerOf(Myself),2363POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2351POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2363POW-2387POW => 2375POW
IF
	CheckStatLT(LastSummonerOf(Myself),2388POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2375POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2388POW-2412POW => 2400POW
IF
	CheckStatLT(LastSummonerOf(Myself),2413POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2400POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2413POW-2437POW => 2425POW
IF
	CheckStatLT(LastSummonerOf(Myself),2438POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2425POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2438POW-2462POW => 2450POW
IF
	CheckStatLT(LastSummonerOf(Myself),2463POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2450POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2463POW-2488POW => 2475POW
IF
	CheckStatLT(LastSummonerOf(Myself),2489POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2475POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2489POW-2514POW => 2501POW
IF
	CheckStatLT(LastSummonerOf(Myself),2515POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2501POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2515POW-2540POW => 2528POW
IF
	CheckStatLT(LastSummonerOf(Myself),2541POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2528POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2541POW-2566POW => 2554POW
IF
	CheckStatLT(LastSummonerOf(Myself),2567POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2554POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2567POW-2593POW => 2580POW
IF
	CheckStatLT(LastSummonerOf(Myself),2594POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2580POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2594POW-2620POW => 2607POW
IF
	CheckStatLT(LastSummonerOf(Myself),2621POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2607POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2621POW-2647POW => 2634POW
IF
	CheckStatLT(LastSummonerOf(Myself),2648POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2634POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2648POW-2674POW => 2661POW
IF
	CheckStatLT(LastSummonerOf(Myself),2675POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2661POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2675POW-2702POW => 2688POW
IF
	CheckStatLT(LastSummonerOf(Myself),2703POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2688POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2703POW-2730POW => 2717POW
IF
	CheckStatLT(LastSummonerOf(Myself),2731POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2717POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2731POW-2758POW => 2745POW
IF
	CheckStatLT(LastSummonerOf(Myself),2759POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2745POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2759POW-2787POW => 2773POW
IF
	CheckStatLT(LastSummonerOf(Myself),2788POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2773POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2788POW-2816POW => 2802POW
IF
	CheckStatLT(LastSummonerOf(Myself),2817POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2802POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2817POW-2845POW => 2831POW
IF
	CheckStatLT(LastSummonerOf(Myself),2846POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2831POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2846POW-2874POW => 2860POW
IF
	CheckStatLT(LastSummonerOf(Myself),2875POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2860POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2875POW-2904POW => 2889POW
IF
	CheckStatLT(LastSummonerOf(Myself),2905POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2889POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2905POW-2934POW => 2920POW
IF
	CheckStatLT(LastSummonerOf(Myself),2935POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2920POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2935POW-2964POW => 2950POW
IF
	CheckStatLT(LastSummonerOf(Myself),2965POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2950POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2965POW-2995POW => 2980POW
IF
	CheckStatLT(LastSummonerOf(Myself),2996POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-2980POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 2996POW-3026POW => 3011POW
IF
	CheckStatLT(LastSummonerOf(Myself),3027POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3011POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3027POW-3057POW => 3042POW
IF
	CheckStatLT(LastSummonerOf(Myself),3058POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3042POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3058POW-3089POW => 3073POW
IF
	CheckStatLT(LastSummonerOf(Myself),3090POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3073POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3090POW-3121POW => 3105POW
IF
	CheckStatLT(LastSummonerOf(Myself),3122POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3105POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3122POW-3153POW => 3138POW
IF
	CheckStatLT(LastSummonerOf(Myself),3154POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3138POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3154POW-3186POW => 3170POW
IF
	CheckStatLT(LastSummonerOf(Myself),3187POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3170POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3187POW-3219POW => 3203POW
IF
	CheckStatLT(LastSummonerOf(Myself),3220POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3203POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3220POW-3252POW => 3236POW
IF
	CheckStatLT(LastSummonerOf(Myself),3253POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3236POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3253POW-3286POW => 3269POW
IF
	CheckStatLT(LastSummonerOf(Myself),3287POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3269POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3287POW-3320POW => 3303POW
IF
	CheckStatLT(LastSummonerOf(Myself),3321POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3303POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3321POW-3354POW => 3338POW
IF
	CheckStatLT(LastSummonerOf(Myself),3355POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3338POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3355POW-3389POW => 3372POW
IF
	CheckStatLT(LastSummonerOf(Myself),3390POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3372POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3390POW-3424POW => 3407POW
IF
	CheckStatLT(LastSummonerOf(Myself),3425POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3407POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3425POW-3459POW => 3442POW
IF
	CheckStatLT(LastSummonerOf(Myself),3460POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3442POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3460POW-3495POW => 3477POW
IF
	CheckStatLT(LastSummonerOf(Myself),3496POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3477POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3496POW-3531POW => 3513POW
IF
	CheckStatLT(LastSummonerOf(Myself),3532POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3513POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3532POW-3567POW => 3550POW
IF
	CheckStatLT(LastSummonerOf(Myself),3568POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3550POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3568POW-3604POW => 3586POW
IF
	CheckStatLT(LastSummonerOf(Myself),3605POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3586POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3605POW-3641POW => 3623POW
IF
	CheckStatLT(LastSummonerOf(Myself),3642POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3623POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3642POW-3678POW => 3660POW
IF
	CheckStatLT(LastSummonerOf(Myself),3679POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3660POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3679POW-3716POW => 3697POW
IF
	CheckStatLT(LastSummonerOf(Myself),3717POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3697POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3717POW-3754POW => 3736POW
IF
	CheckStatLT(LastSummonerOf(Myself),3755POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3736POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3755POW-3793POW => 3774POW
IF
	CheckStatLT(LastSummonerOf(Myself),3794POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3774POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3794POW-3832POW => 3813POW
IF
	CheckStatLT(LastSummonerOf(Myself),3833POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3813POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3833POW-3871POW => 3852POW
IF
	CheckStatLT(LastSummonerOf(Myself),3872POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3852POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3872POW-3911POW => 3891POW
IF
	CheckStatLT(LastSummonerOf(Myself),3912POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3891POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3912POW-3951POW => 3932POW
IF
	CheckStatLT(LastSummonerOf(Myself),3952POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3932POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3952POW-3992POW => 3972POW
IF
	CheckStatLT(LastSummonerOf(Myself),3993POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-3972POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 3993POW-4033POW => 4013POW
IF
	CheckStatLT(LastSummonerOf(Myself),4034POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4013POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4034POW-4074POW => 4054POW
IF
	CheckStatLT(LastSummonerOf(Myself),4075POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4054POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4075POW-4116POW => 4095POW
IF
	CheckStatLT(LastSummonerOf(Myself),4117POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4095POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4117POW-4158POW => 4138POW
IF
	CheckStatLT(LastSummonerOf(Myself),4159POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4138POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4159POW-4201POW => 4180POW
IF
	CheckStatLT(LastSummonerOf(Myself),4202POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4180POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4202POW-4244POW => 4223POW
IF
	CheckStatLT(LastSummonerOf(Myself),4245POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4223POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4245POW-4287POW => 4266POW
IF
	CheckStatLT(LastSummonerOf(Myself),4288POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4266POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4288POW-4331POW => 4309POW
IF
	CheckStatLT(LastSummonerOf(Myself),4332POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4309POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4332POW-4375POW => 4354POW
IF
	CheckStatLT(LastSummonerOf(Myself),4376POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4354POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4376POW-4420POW => 4398POW
IF
	CheckStatLT(LastSummonerOf(Myself),4421POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4398POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4421POW-4465POW => 4443POW
IF
	CheckStatLT(LastSummonerOf(Myself),4466POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4443POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4466POW-4511POW => 4488POW
IF
	CheckStatLT(LastSummonerOf(Myself),4512POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4488POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4512POW-4557POW => 4535POW
IF
	CheckStatLT(LastSummonerOf(Myself),4558POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4535POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4558POW-4604POW => 4581POW
IF
	CheckStatLT(LastSummonerOf(Myself),4605POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4581POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4605POW-4651POW => 4628POW
IF
	CheckStatLT(LastSummonerOf(Myself),4652POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4628POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4652POW-4699POW => 4675POW
IF
	CheckStatLT(LastSummonerOf(Myself),4700POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4675POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4700POW-4747POW => 4723POW
IF
	CheckStatLT(LastSummonerOf(Myself),4748POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4723POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4748POW-4795POW => 4772POW
IF
	CheckStatLT(LastSummonerOf(Myself),4796POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4772POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4796POW-4844POW => 4820POW
IF
	CheckStatLT(LastSummonerOf(Myself),4845POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4820POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4845POW-4893POW => 4869POW
IF
	CheckStatLT(LastSummonerOf(Myself),4894POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4869POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4894POW-4943POW => 4918POW
IF
	CheckStatLT(LastSummonerOf(Myself),4944POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4918POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4944POW-4993POW => 4969POW
IF
	CheckStatLT(LastSummonerOf(Myself),4994POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-4969POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 4994POW-5044POW => 5019POW
IF
	CheckStatLT(LastSummonerOf(Myself),5045POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5019POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5045POW-5095POW => 5070POW
IF
	CheckStatLT(LastSummonerOf(Myself),5096POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5070POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5096POW-5147POW => 5121POW
IF
	CheckStatLT(LastSummonerOf(Myself),5148POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5121POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5148POW-5199POW => 5174POW
IF
	CheckStatLT(LastSummonerOf(Myself),5200POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5174POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5200POW-5252POW => 5226POW
IF
	CheckStatLT(LastSummonerOf(Myself),5253POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5226POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5253POW-5306POW => 5279POW
IF
	CheckStatLT(LastSummonerOf(Myself),5307POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5279POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5307POW-5360POW => 5334POW
IF
	CheckStatLT(LastSummonerOf(Myself),5361POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5334POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5361POW-5415POW => 5388POW
IF
	CheckStatLT(LastSummonerOf(Myself),5416POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5388POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5416POW-5470POW => 5443POW
IF
	CheckStatLT(LastSummonerOf(Myself),5471POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5443POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5471POW-5526POW => 5498POW
IF
	CheckStatLT(LastSummonerOf(Myself),5527POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5498POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5527POW-5582POW => 5555POW
IF
	CheckStatLT(LastSummonerOf(Myself),5583POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5555POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5583POW-5639POW => 5611POW
IF
	CheckStatLT(LastSummonerOf(Myself),5640POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5611POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5640POW-5696POW => 5668POW
IF
	CheckStatLT(LastSummonerOf(Myself),5697POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5668POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5697POW-5754POW => 5725POW
IF
	CheckStatLT(LastSummonerOf(Myself),5755POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5725POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5755POW-5813POW => 5784POW
IF
	CheckStatLT(LastSummonerOf(Myself),5814POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5784POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5814POW-5872POW => 5843POW
IF
	CheckStatLT(LastSummonerOf(Myself),5873POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5843POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5873POW-5932POW => 5902POW
IF
	CheckStatLT(LastSummonerOf(Myself),5933POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5902POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5933POW-5992POW => 5963POW
IF
	CheckStatLT(LastSummonerOf(Myself),5993POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-5963POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 5993POW-6053POW => 6023POW
IF
	CheckStatLT(LastSummonerOf(Myself),6054POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6023POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6054POW-6115POW => 6084POW
IF
	CheckStatLT(LastSummonerOf(Myself),6116POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6084POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6116POW-6177POW => 6147POW
IF
	CheckStatLT(LastSummonerOf(Myself),6178POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6147POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6178POW-6240POW => 6209POW
IF
	CheckStatLT(LastSummonerOf(Myself),6241POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6209POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6241POW-6303POW => 6272POW
IF
	CheckStatLT(LastSummonerOf(Myself),6304POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6272POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6304POW-6367POW => 6336POW
IF
	CheckStatLT(LastSummonerOf(Myself),6368POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6336POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6368POW-6432POW => 6400POW
IF
	CheckStatLT(LastSummonerOf(Myself),6433POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6400POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6433POW-6497POW => 6465POW
IF
	CheckStatLT(LastSummonerOf(Myself),6498POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6465POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6498POW-6563POW => 6530POW
IF
	CheckStatLT(LastSummonerOf(Myself),6564POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6530POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6564POW-6630POW => 6597POW
IF
	CheckStatLT(LastSummonerOf(Myself),6631POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6597POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6631POW-6697POW => 6664POW
IF
	CheckStatLT(LastSummonerOf(Myself),6698POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6664POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6698POW-6765POW => 6731POW
IF
	CheckStatLT(LastSummonerOf(Myself),6766POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6731POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6766POW-6834POW => 6800POW
IF
	CheckStatLT(LastSummonerOf(Myself),6835POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6800POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6835POW-6903POW => 6869POW
IF
	CheckStatLT(LastSummonerOf(Myself),6904POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6869POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6904POW-6973POW => 6939POW
IF
	CheckStatLT(LastSummonerOf(Myself),6974POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-6939POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 6974POW-7044POW => 7009POW
IF
	CheckStatLT(LastSummonerOf(Myself),7045POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7009POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7045POW-7115POW => 7080POW
IF
	CheckStatLT(LastSummonerOf(Myself),7116POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7080POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7116POW-7187POW => 7152POW
IF
	CheckStatLT(LastSummonerOf(Myself),7188POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7152POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7188POW-7260POW => 7224POW
IF
	CheckStatLT(LastSummonerOf(Myself),7261POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7224POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7261POW-7334POW => 7297POW
IF
	CheckStatLT(LastSummonerOf(Myself),7335POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7297POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7335POW-7408POW => 7372POW
IF
	CheckStatLT(LastSummonerOf(Myself),7409POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7372POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7409POW-7483POW => 7446POW
IF
	CheckStatLT(LastSummonerOf(Myself),7484POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7446POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7484POW-7559POW => 7521POW
IF
	CheckStatLT(LastSummonerOf(Myself),7560POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7521POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7560POW-7636POW => 7598POW
IF
	CheckStatLT(LastSummonerOf(Myself),7637POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7598POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7637POW-7713POW => 7675POW
IF
	CheckStatLT(LastSummonerOf(Myself),7714POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7675POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7714POW-7791POW => 7753POW
IF
	CheckStatLT(LastSummonerOf(Myself),7792POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7753POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7792POW-7870POW => 7831POW
IF
	CheckStatLT(LastSummonerOf(Myself),7871POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7831POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7871POW-7950POW => 7910POW
IF
	CheckStatLT(LastSummonerOf(Myself),7951POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7910POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 7951POW-8031POW => 7991POW
IF
	CheckStatLT(LastSummonerOf(Myself),8032POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-7991POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8032POW-8112POW => 8072POW
IF
	CheckStatLT(LastSummonerOf(Myself),8113POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8072POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8113POW-8194POW => 8154POW
IF
	CheckStatLT(LastSummonerOf(Myself),8195POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8154POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8195POW-8277POW => 8236POW
IF
	CheckStatLT(LastSummonerOf(Myself),8278POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8236POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8278POW-8361POW => 8319POW
IF
	CheckStatLT(LastSummonerOf(Myself),8362POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8319POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8362POW-8446POW => 8404POW
IF
	CheckStatLT(LastSummonerOf(Myself),8447POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8404POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8447POW-8531POW => 8489POW
IF
	CheckStatLT(LastSummonerOf(Myself),8532POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8489POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8532POW-8617POW => 8575POW
IF
	CheckStatLT(LastSummonerOf(Myself),8618POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8575POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8618POW-8704POW => 8661POW
IF
	CheckStatLT(LastSummonerOf(Myself),8705POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8661POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8705POW-8792POW => 8749POW
IF
	CheckStatLT(LastSummonerOf(Myself),8793POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8749POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8793POW-8881POW => 8837POW
IF
	CheckStatLT(LastSummonerOf(Myself),8882POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8837POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8882POW-8971POW => 8926POW
IF
	CheckStatLT(LastSummonerOf(Myself),8972POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-8926POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 8972POW-9062POW => 9017POW
IF
	CheckStatLT(LastSummonerOf(Myself),9063POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9017POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9063POW-9154POW => 9108POW
IF
	CheckStatLT(LastSummonerOf(Myself),9155POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9108POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9155POW-9247POW => 9201POW
IF
	CheckStatLT(LastSummonerOf(Myself),9248POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9201POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9248POW-9340POW => 9294POW
IF
	CheckStatLT(LastSummonerOf(Myself),9341POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9294POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9341POW-9434POW => 9388POW
IF
	CheckStatLT(LastSummonerOf(Myself),9435POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9388POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9435POW-9529POW => 9482POW
IF
	CheckStatLT(LastSummonerOf(Myself),9530POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9482POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9530POW-9625POW => 9578POW
IF
	CheckStatLT(LastSummonerOf(Myself),9626POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9578POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9626POW-9722POW => 9674POW
IF
	CheckStatLT(LastSummonerOf(Myself),9723POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9674POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9723POW-9820POW => 9772POW
IF
	CheckStatLT(LastSummonerOf(Myself),9821POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9772POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9821POW-9919POW => 9870POW
IF
	CheckStatLT(LastSummonerOf(Myself),9920POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9870POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END

// NPC XP 9920POW-10019POW => 9970POW
IF
	CheckStatLT(LastSummonerOf(Myself),10020POW,XP)
THEN
	RESPONSE #100
		IncrementGlobal("XPSYNC_GRANT","LOCALS",-9970POW)
		ChangeAIScript("xpsgrant",OVERRIDE)
END
